name = "roblox-proxy"
compatibility_date = "2024-09-28"
pages_build_output_dir = "./dist"

# Fuck off Cloudflare
workers_dev = false
send_metrics = false

# Force enable keeping logs
[observability]
enabled = true
